name: huji_hackathon
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.1.1
  firebase_storage: ^8.0.6
  cloud_firestore: ^2.1.0
  firebase_auth: ^1.1.4
  image_picker: ^0.7.5
  permission_handler: ^7.1.0
  provider: ^5.0.0
  flutter_spinkit: ^5.0.0
  google_sign_in: ^5.0.3
  auth_buttons: ^1.0.1+3

  splashscreen: ^1.3.5
  flutter_signin_button: ^2.0.0
  assorted_layout_widgets: ^4.0.9
  google_fonts: ^2.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/home_button.png
    - assets/images/Amit.Edry@gmail.com25.jpeg
    - assets/images/karmila_kisalon.jpeg
    - assets/images/KarmilaKisalon-Route.png
    
    - assets/images/Tsuf.Gamlieli@gmail.com26.jpeg
    - assets/images/TurmusHill.jpeg
    - assets/images/TurmusHill-Route.png

    
    # Guy added these assets
    - assets/images/Daniella.Leshem@gmail.com27.jpeg
    - assets/images/David.Soffer@gmail.com24.jpeg
    - assets/images/Gili.Shor@gmail.com27.jpeg
    - assets/images/Maayan.Segal@mail.huji.ac.il26.jpeg
    - assets/images/Netta.Meir@gmail.com27.jpeg
    - assets/images/Pavel.Dmitrochenko@gmail.com25.jpeg
    - assets/images/Roni.Birger@gmail.com26.jpeg
    - assets/images/Roni.Shem-Tov@gmail.com24.jpeg
    - assets/images/Rubi.Levinstein@gmail.com29.jpeg
    - assets/images/Shay.Cohen@mail.huji.ac.il25.jpeg
    - assets/images/Shir.Kedmi@gmail.com24.jpeg
    - assets/images/Tomer.Machluf@huji.mail.ac.il25.jpeg
    - assets/images/Yoav.Timor@gmail.com27.jpeg

    #Guy added trips photos
    - assets/images/ArugotStream.jpeg
    - assets/images/ArugotStream-Route.jpeg
    - assets/images/CampingShalom.jpeg
    - assets/images/CampingShalom-Route.png
    - assets/images/EinKarem.jpg
    - assets/images/EinKarem-Route.jpg
    - assets/images/EinMaboa.jpeg
    - assets/images/EinMaboa-Route.jpeg
    - assets/images/EmekHamazleva.jpeg
    - assets/images/EmekHamazleva-Route.png
    - assets/images/JerusForest.jpeg
    - assets/images/JerusForest-Route.png
    - assets/images/KazivStream.jpeg
    - assets/images/KazivStream-Route.jpeg
    - assets/images/OldCity.jpeg
    - assets/images/OldCity-Route.png
    - assets/images/RamonCrater.jpeg
    - assets/images/RamonCrater-Route.jpeg
    - assets/images/TurmusHill.jpeg
    - assets/images/TurmusHill-Route.png

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages