import 'user2.dart';

class DummyUsers2 {
  static get all_users => <MyUser2>[
        MyUser2(
            idUser: '0',
            name: "Amit Edry",
            urlAvatar: "assets/images/Amit.Edry@gmail.com25.jpeg",
            age: 27,
            description: "אוהב לקרוא ספרים, טיול רגלי וג'יפים",
            email: "AmitEdry@gmail.com",
            password: "123456",
            trips: [],
            created: 2,
            attended: 10,
            attending: 2),
        MyUser2(
            idUser: '1',
            name: "Daniella Leshem",
            urlAvatar: "assets/images/Daniella.Leshem@gmail.com27.jpeg",
            age: 24,
            description: "אוהבת טיולים בדרום, ובמקומות היסטוריים",
            email: "DaniellaLeshem@gmail.com",
            password: "123456",
            trips: [],
            created: 3,
            attended: 4,
            attending: 1),
        MyUser2(
            idUser: '2',
            name: "David Soffer",
            urlAvatar: "assets/images/David.Soffer@gmail.com24.jpeg",
            age: 24,
            description: "מעדיף טיולים רכובים ובסופי שבוע",
            email: "DavidSoffer@gmail.com",
            password: "123456",
            trips: [],
            created: 10,
            attended: 11,
            attending: 2),
        MyUser2(
            idUser: '3',
            name: "Gili Shor",
            urlAvatar: "assets/images/Gili.Shor@gmail.com27.jpeg",
            age: 27,
            description: "טיולים וכמה שיותר קרוב לים",
            email: "GiliShor@gmail.com",
            password: "123456",
            trips: [],
            created: 3,
            attended: 4,
            attending: 2),
        MyUser2(
            idUser: '4',
            name: "Mayyan Segal",
            urlAvatar: "assets/images/Maayan.Segal@mail.huji.ac.il26.jpeg",
            age: 26,
            description: "הליכות, יער ומדברים",
            email: "MayanSegal@gmail.com",
            password: "123456",
            trips: [],
            created: 11,
            attended: 22,
            attending: 3),
        MyUser2(
            idUser: '5',
            name: "Netta Meir",
            urlAvatar: "assets/images/Netta.Meir@gmail.com27.jpeg",
            age: 27,
            description: "חברים חדשים, שיחות עומק וקומזיץ",
            email: "assets/images/",
            password: "123456",
            trips: [],
            created: 4,
            attended: 15,
            attending: 6),
        MyUser2(
            idUser: '6',
            name: "Pavel Dmitrochenko",
            urlAvatar: "assets/images/Pavel.Dmitrochenko@gmail.com25.jpeg",
            age: 25,
            description: "על האשים, מפלים וטיולים בצפון",
            email: "PavelDmitrochenko@gmail.com",
            password: "123456",
            trips: [],
            created: 2,
            attended: 15,
            attending: 4),
        MyUser2(
            idUser: '7',
            name: "Roni Birger",
            urlAvatar: "assets/images/Roni.Birger@gmail.com26.jpeg",
            age: 26,
            description: "אוכל טוב, יין וטיולי הרים",
            email: "RoniBirger@gmail.com",
            password: "123456",
            trips: [],
            created: 4,
            attended: 11,
            attending: 3),
        MyUser2(
            idUser: '8',
            name: "Roni Shem-Tov",
            urlAvatar: "assets/images/Roni.Shem-Tov@gmail.com24.jpeg",
            age: 24,
            description: "כמה שיותר מוקדם בבוקר לסוע למדבר ולהמשיך משם",
            email: "RoniShemtov@gmail.com",
            password: "123456",
            trips: [],
            created: 2,
            attended: 15,
            attending: 3),
        MyUser2(
            idUser: '9',
            name: "Rubi Levinstein",
            urlAvatar: "assets/images/Rubi.Levinstein@gmail.com29.jpeg",
            age: 29,
            description: "מעדיף טיולים רכובים ובסופי שבוע",
            email: "Rubi.Levinstein@gmail.com",
            password: "123456",
            trips: [],
            created: 11,
            attended: 35,
            attending: 14),
        MyUser2(
            idUser: '10',
            name: "Shay Cohen",
            urlAvatar: "assets/images/Shay.Cohen@mail.huji.ac.il25.jpeg",
            age: 25,
            description: "ללכת, יער ומדברים",
            email: "Shay.cohen@gmail.com",
            password: "123456",
            trips: [],
            created: 3,
            attended: 19,
            attending: 4),
        MyUser2(
            idUser: '11',
            name: "Shir Kedmi",
            urlAvatar: "assets/images/Shir.Kedmi@gmail.com24.jpeg",
            age: 24,
            description: "אוהב לקרוא ספרים, טיול רגלי וג'יפים",
            email: "Shir.Kedmi@gmail.com",
            password: "123456",
            trips: [],
            created: 4,
            attended: 16,
            attending: 2),
        MyUser2(
            idUser: '12',
            name: "Tomer Machluf",
            urlAvatar: "assets/images/Shir.Kedmi@gmail.com24.jpeg",
            age: 25,
            description: "אופנועים, טיולי ג'יפים עם החברים ואוכל טוב",
            email: "Tomer.Machluf@gmail.com",
            password: "123456",
            trips: [],
            created: 3,
            attended: 13,
            attending: 4),
        MyUser2(
            idUser: '13',
            name: "Tsuf Gamlieli",
            urlAvatar: "assets/images/Tsuf.Gamlieli@gmail.com26.jpeg",
            age: 26,
            description:
                "סטודנט בתל אביב, הקורסים פה ממש קלים. נהנה בטבע כי יש לי מלא זמן.",
            email: "Tsuf.Gamlieli@gmail.com",
            password: "123456",
            trips: [],
            created: 17,
            attended: 33,
            attending: 7),
        MyUser2(
            idUser: '14',
            name: "Yoav Timor",
            urlAvatar: "assets/images/Yoav.Timor@gmail.com27.jpeg",
            age: 27,
            description:
                "סטודנט למדעי המחשב וקוגניציה, חובב אקסטרים, ובעלים של נלה המתוקה",
            email: "Yoav.Timor@gmail.com",
            address: "Jerusalem",
            password: "123456",
            trips: [],
            created: 1,
            attended: 3,
            attending: 1),
      ];
}
